version: "3"
services:
  database:
    hostname: database
    image: postgres:15.1-alpine
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - elof_database:/var/lib/postgresql/data
    networks:
      nw:
        aliases:
          - database
  bot:
      build: bot/
      command: /srv/telegram_admin/run.sh
      environment:
        - DATABASE_URL=postgresql://postgres:postgres@database/ytb
        - BOT_TOKEN=5877474089:AAH7wEkk88ghYtycRecKXik9SZ5IjO1ESjI
        - OPEN_WEATHER_TOKEN=45751c89bc82fb7afa7ca0b2093a88f6
      ports:
        - 88:88
      depends_on:
        - database
      networks:
        nw:
          aliases:
            - bot

networks:
  nw:
  share:
    driver:
      bridge

volumes:
  elof_database:
