# Generated by Django 4.1.7 on 2023-02-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonum_app', '0007_alter_homework_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonum_app.homeworktype', verbose_name='Тип домашней работы'),
        ),
    ]
