# Generated by Django 4.1.7 on 2023-02-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonum_app', '0014_alter_timetable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonum_app.teacher'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='week_type',
            field=models.IntegerField(choices=[(0, 'Четная'), (1, 'Нечетная'), (2, 'Все недели')], verbose_name='Четность недели'),
        ),
    ]
