# Generated by Django 4.1.7 on 2023-02-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonum_app', '0017_alter_timebot_end_alter_timebot_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebot',
            name='end2',
            field=models.TextField(default='', verbose_name='Конец'),
        ),
        migrations.AddField(
            model_name='timebot',
            name='start1',
            field=models.TextField(default='', verbose_name='Начало'),
        ),
    ]
