# Generated by Django 4.1.3 on 2023-02-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonum_app', '0018_timebot_end2_timebot_start1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='exp_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
    ]
