# Generated by Django 4.1.3 on 2023-02-26 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bonum_app', '0019_alter_homework_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='exp_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дедлайн'),
            preserve_default=False,
        ),
    ]
