# Generated by Django 4.1.3 on 2022-12-04 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonum_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBotUser',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nickname', models.TextField(blank=True)),
                ('full_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_chat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bonum_app.adminbotuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Privacy',
        ),
    ]
