# Generated by Django 4.1.7 on 2023-02-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonum_app', '0004_alter_teacher_options_homework_group_timetable_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Название группы'),
        ),
    ]
