# Generated by Django 4.1.3 on 2023-01-29 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonum_app', '0006_group_name_alter_homework_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonum_app.teacher'),
        ),
    ]
