# Generated by Django 4.1.7 on 2023-02-19 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonum_app', '0006_alter_homework_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonum_app.discipline', verbose_name='Дисциплина'),
        ),
    ]
