# Generated by Django 4.1.3 on 2023-01-29 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonum_app', '0009_remove_timetable_group_timetable_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='group',
        ),
        migrations.AddField(
            model_name='timetable',
            name='group',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='bonum_app.group', verbose_name='Группа'),
        ),
    ]
