# Generated by Django 4.1.3 on 2023-01-29 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonum_app', '0012_remove_timetable_group_timetable_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonum_app.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonum_app.timebot', verbose_name='Время'),
        ),
    ]
