# Generated by Django 4.1.7 on 2023-02-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonum_app', '0012_alter_timetable_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='first_time_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.TextField(blank=True, verbose_name='Аудитория'),
        ),
    ]
