# Generated by Django 4.1.7 on 2023-02-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonum_app', '0016_alter_timebot_end_alter_timebot_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebot',
            name='end',
            field=models.TextField(verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='timebot',
            name='start',
            field=models.TextField(verbose_name='Начало'),
        ),
    ]
